const motList = ["Manger", "Histoire", "Un", "Plafond",
 "Arbre", "Château", "Amour", "Rouge", "École", "Voiture",
"Livre", "Ordinateur", "Téléphone", "Table", "Chien", "Chat", "Pomme", "Montagne", "Rivière",
"Mer", "Soleil", "Lune", "Étoile", "Fleur", "Parc", "Ville", "Route", "Pont", "Aéroport",
"Train", "Avion", "Bateau", "Vélo", "Chaise", "Bureau", "Fenêtre", "Porte", "Clé", "Cahier",
"Stylo", "Crayon", "Gomme", "Sac", "Chaussure", "Chapeau", "Chemise", "Pantalon", "Robe", "Manteau",
"Écharpe", "Gant", "Montre", "Bracelet", "Collier", "Bague", "Boucle", "Oreille", "Nez", "Bouche",
"Main", "Pied", "Doigt", "Bras", "Jambe", "Tête", "Cœur", "Cerveau", "Poumon", "Estomac",
"Cheveux", "Yeux", "Sourcil", "Cils", "Jardin", "Fruits", "Légume", "Viande", "Poisson", "Pain",
"Fromage", "Lait", "Eau", "Jus", "Vin", "Café", "Thé", "Sucre", "Sel", "Poivre",
"Huile", "Beurre", "Œuf", "Gâteau", "Chocolat", "Bonbon", "Glace", "Yaourt", "Biscuit", "Pâtes",
"Riz", "Soupe", "Pizza", "Salade", "Frite", "Saucisse", "Sandwich", "Tarte", "Miel", "Orange",
"Banane", "Poire", "Raisin", "Citron", "Fraise", "Cerise", "Tomate", "Carotte", "Laitue", "Poireau",
"Oignon", "Ail", "Champignon", "Courgette", "Épinard", "Aubergine", "Patate", "Haricot", "Maïs", "Croissant",
"Baguette", "Crêpe", "Gaufre", "Omelette", "Quiche", "Hamburger", "Moutarde", "Sauce", "Fraise", "Pêche",
"Abricot", "Mûre", "Myrtille", "Framboise", "Grenade", "Mangue", "Ananas", "Noix", "Amande", "Noisette",
"Pistache", "Pacane", "Cacahuète", "Châtaigne", "Prune", "Dattes", "Figues", "Pruneau", "Coco", "Papaye",
"Exotique", "Sirop", "Chantilly", "Compote", "Brûlée", "Macaron", "Éclair", "Religieuse", "Millefeuille",
"Profiterole", "Épaule", "Ciel", "Nuage", "Pluie", "Neige", "Vent", "Foudre", "Tonnerre", "Éclair",
"Tempête", "Orage", "Arc", "En", "Ciel", "Matin", "Midi", "Soir", "Nuit", "Saison",
"Printemps", "Été", "Automne", "Hiver", "Janvier", "Février", "Mars", "Avril", "Mai", "Juin",
"Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre", "Jour", "Semaine", "Mois", "Année",
"Siècle", "Minute", "Seconde", "Heure", "Horloge", "Calendrier", "Montre", "Réveil", "Lundi", "Mardi",
"Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche", "Week-end", "Lumière", "Sombre", "Clair", "Ombre",
"Couleur", "Rouge", "Bleu", "Vert", "Jaune", "Rose", "Orange", "Violet", "Marron", "Noir",
"Blanc", "Gris", "Doux", "Dur", "Mou", "Sec", "Humide", "Lourd", "Léger", "Chaud",
"Froid", "Tiède", "Gelé", "Brûlant", "Fort", "Faible", "Grand", "Petit", "Long", "Court",
"Gros", "Mince", "Large", "Étroit", "Haut", "Bas", "Épais", "Fin", "Rond", "Carré",
"Triangle", "Rectangle", "Cercle", "Oval", "Point", "Ligne", "Droite", "Courbe", "Angle", "Coin",
"Bord", "Centre", "Dessus", "Dessous", "Devant", "Derrière", "Côté", "Intérieur", "Extérieur", "Entrée",
"Sortie", "Ouvert", "Fermé", "Devant", "Derrière", "Côté", "Gauche", "Droite", "Proche", "Loin",
"Partout", "Nulle", "Part", "Quelque", "Part", "Ici", "Là", "Maintenant", "Demain", "Hier",
"Tôt", "Tard", "Jamais", "Toujours", "Parfois", "Souvent", "Rarement", "Déjà", "Encore", "Finalement",
"Prudemment", "Lentement", "Rapidement", "Heureusement", "Malheureusement", "Sérieusement", "Facilement", "Difficilement", "Poliment", "Impatiemment",
"Amicalement", "Passionnément", "Sagement", "Curieusement", "Malicieusement", "Doucement", "Férocement", "Violemment", "Tendrement", "Vivement",
"Évidemment", "Heureusement", "Tranquillement", "Brièvement", "Précisément", "Parfaitement", "Lentement", "Facilement", "Difficilement", "Profondément",
"Léger", "Fortement", "Sûrement", "Possiblement", "Certainement", "Probablement", "Apparemment", "Indéniablement", "Inévitablement", "Gaiement",
"Joyeusement", "Sombrement", "Tristement", "Plaisamment", "Gracieusement", "Généreusement", "Méchant", "Brutalement", "Dangereusement", "Sainement",
"Intelligemment", "Sagement", "Curieusement", "Attentivement", "Discrètement", "Habilement", "Timidement", "Courageusement", "Loyalement", "Honnêtement",
"Poliment", "Impoliment", "Respectueusement", "Brillamment", "Magnifiquement", "Merveilleusement", "Délicatement", "Médiocrement", "Chaleureusement", "Froideur",
"Audacieusement", "Imprudemment", "Fidèlement", "Affection", "Bienveillance", "Compassion", "Dignité", "Respect", "Générosité",
"Honest", "Intégrité", "Justice", "Moralité", "Noblesse", "Patience", "Sagesse", "Tolérance", "Vertu",
"Amitié", "Bonheur", "Chance", "Courage", "Espoir", "Félicité", "Liberté", "Paix", "Sécurité",
"Vérité", "Amusement", "Art", "Beauté", "Créativité", "Détente", "Divertissement", "Émotion", "Énergie",
"Engagement", "Enthousiasme", "Équilibre", "Excitation", "Expression", "Fascination", "Fierté", "Inspiration", "Joie", "Passion",
"Puissance", "Réflexion", "Rythme", "Satisfaction", "Sérénité", "Silence", "Simplicité", "Stimulation", "Sympathie",
"Tension", "Unité", "Valeur", "Vitalité", "Volonté", "Zèle", "Amélioration", "Apprentissage", "Autonomie",
"Croissance", "Évolution", "Formation", "Habileté", "Indépendance", "Innovation", "Initiative", "Maîtrise",
"Motivation", "Progrès", "Réussite", "Accomplissement", "Ambition", "Détermination", "Succès", "Victoire",
"Assurance"];
const phraseList = ["Je veux un nouveau téléphone portable",
    "La plage est couverte de sable fin",
    "Le chat dort paisiblement sur le lit",
    "Pouvons-nous partir en vacances cet été",
    "Le ciel est rempli d'étoiles brillantes",
    "Elle porte une belle robe bleue",
    "L'ordinateur fonctionne parfaitement bien aujourd'hui",
    "Ils regardent un film d'action ce soir",
    "Nous avons acheté des meubles en bois",
    "Le chien joue avec une balle rouge",
    "Les enfants dessinent sur le tableau blanc",
    "La voiture est garée devant la maison",
    "Il fait chaud pendant tout l'été ici",
    "Le livre est posé sur l'étagère",
    "Elle prépare un gâteau au chocolat délicieux",
    "Les oiseaux chantent tôt le matin",
    "Je veux apprendre à jouer du piano",
    "Le jardin est plein de fleurs colorées",
    "Pouvons-nous visiter le musée ce week-end",
    "Le train arrive à la gare centrale",
    "Il lit un roman policier passionnant",
    "La mer est calme et paisible aujourd'hui",
    "L'écran affiche une image claire et nette",
    "Nous mangeons un repas en famille ce soir",
    "Les arbres sont remplis de feuilles vertes",
    "Je veux acheter une nouvelle voiture rouge",
    "Pouvons-nous planter des légumes dans le jardin",
    "L'herbe est mouillée par la rosée du matin",
    "Les enfants jouent dans le parc après l'école",
    "La maison est décorée pour Noël",
    "Je veux un café avec du lait",
    "Pouvons-nous sortir dîner au restaurant italien",
    "Le chat est assis sur la fenêtre ensoleillée",
    "Elle lit un livre de science-fiction captivant",
    "La montagne est couverte de neige en hiver",
    "Nous marchons le long de la plage déserte",
    "Le soleil se couche derrière les montagnes",
    "Les enfants rient en jouant dans le jardin",
    "Je veux visiter Paris au printemps prochain",
    "Pouvons-nous aller au cinéma ce soir",
    "Le chien aboie contre les passants dans la rue",
    "L'écran est rempli de pixels colorés",
    "La ville est animée le soir",
    "Je veux apprendre à cuisiner des plats italiens",
    "Pouvons-nous organiser une fête d'anniversaire surprise",
    "Les fleurs sont en pleine floraison ce printemps",
    "Il a acheté un nouveau vélo bleu",
    "Nous avons décoré la maison pour la fête",
    "Le ciel est clair après la tempête",
    "Le chat grimpe sur l'arbre dans le jardin",
    "Je veux acheter un livre d'art moderne",
    "Pouvons-nous prendre un taxi pour rentrer chez nous",
    "L'ordinateur est connecté à Internet sans problème",
    "La table est mise pour le dîner de ce soir",
    "Le chien est en train de mâcher un os",
    "La mer est agitée à cause du vent fort",
    "Je veux un sandwich avec du jambon et du fromage",
    "Pouvons-nous visiter la galerie d'art demain",
    "Le film commence à huit heures du soir",
    "Les enfants adorent jouer avec leurs nouveaux jouets",
    "Le chat regarde par la fenêtre en silence",
    "L'écran de la télévision est grand et clair",
    "La plage est pleine de coquillages colorés",
    "Je veux acheter un nouveau sac à main",
    "Pouvons-nous partir en randonnée ce week-end",
    "Le jardin est rempli de papillons en été",
    "Les arbres changent de couleur en automne",
    "Elle joue du violon avec beaucoup de talent",
    "Le ciel est couvert de nuages sombres aujourd'hui",
    "Le chien court joyeusement dans le parc",
    "Je veux un vélo pour aller à l'école",
    "Pouvons-nous manger une glace après le dîner",
    "Les fleurs du jardin sentent très bon",
    "La ville est pleine de touristes en été",
    "L'ordinateur a besoin d'une mise à jour importante",
    "Le livre est rempli d'histoires intéressantes",
    "Le chat s'étire sur le tapis moelleux",
    "Je veux voir le lever du soleil demain matin",
    "Pouvons-nous acheter des billets pour le concert",
    "Le film est une comédie très amusante",
    "Le ciel est dégagé pour observer les étoiles",
    "Le jardin est un endroit calme et paisible",
    "La mer est d'un bleu profond et clair",
    "Je veux peindre les murs de ma chambre",
    "Pouvons-nous adopter un chat au refuge animalier",
    "Les enfants adorent les gâteaux faits maison",
    "Le chien est très obéissant et fidèle",
    "Le soleil brille fort en milieu de journée",
    "L'écran est rempli de chiffres et de lettres",
    "La plage est un endroit idéal pour se détendre",
    "Je veux un café noir sans sucre",
    "Pouvons-nous aller à la montagne cet hiver",
    "Les oiseaux volent haut dans le ciel bleu",
    "La ville est magnifique pendant la nuit",
    "L'ordinateur est éteint pour économiser de l'énergie",
    "Le livre est ouvert à la dernière page",
    "Le chat ronronne doucement sur les genoux",
    "Je veux une nouvelle paire de chaussures confortables",
    "Pouvons-nous inviter des amis à dîner ce soir",
    "Les enfants adorent les parcs d'attractions colorés"]

const msgVictoire = "Un parfait BG !";
const msgEchec = "Presque ! Reesaie dans une nouvelle partie !";
const msgMaxScore = "GG ! Tu as battue ton record !";
const mdjQuestion = "Veux tu jouer avec des mots ou des phrases ? 0 pour mot, 2 pour phrase.";
const mdjQuestionInf = "Mode infinie ? Si oui fait 1 sinon 0";
const infDefault = "En mode infini, une faute te fait perdre le jeu !";


//t[0] = scoreMaxMotNormal
//t[1] = scoreMaxMotInfinite
//t[2] = scoreMaxPhraseNormal
//t[3] = scoreMaxPhraseInfinite

let scoreMaxTab = [0,0,0,0];

//t[0] = nbrMaxMotOuPhraseNormal
//t[1] = nbrMaxMotOuPhraseInfinite
let nbrMotPhraseMaxTab = [10,Number.MAX_VALUE];

const normDefault = "Il y a par défaut "+nbrMotPhraseMaxTab[0]+" mots dans ce mode, une faute et c'est perdu !";
const norpDefault = "Il y a par défaut "+nbrMotPhraseMaxTab[0]+" phrases dans ce mode, une faute et c'est perdu !";